/**
 * The honesty component.
 *
 * Every market number in this application renders through here. Given a
 * `Sourced<T>` it shows the value with a status chip, and given an
 * `Unavailable` it shows the literal words **"Live market data unavailable"**
 * plus the reason — never a dash pretending to be a price, never a zero, never
 * a stale number wearing a live badge.
 *
 * Because `Sourced<T>` is a discriminated union, TypeScript will not let a
 * caller forget the unavailable branch.
 */
import * as React from 'react';
import { AlertCircle, Info } from 'lucide-react';
import { cn } from '@/lib/utils';
import { Tooltip } from '@/components/ui';
import { relativeTime, istTime, humanise } from '@/lib/format';
import type { Sourced, DataStatus, Provenance } from '@/types/api';
import { isAvailable } from '@/types/api';

// ── status chip ─────────────────────────────────────────────────────────────

const STATUS_COPY: Record<DataStatus, { label: string; help: string }> = {
  live: {
    label: 'Live',
    help: 'Received from the data provider within the freshness budget for this data type.',
  },
  delayed: {
    label: 'Delayed',
    help: 'Older than the freshness budget for this data type. It is real data, but not current.',
  },
  closed: {
    label: 'At close',
    help: 'The market session is not in progress. This is the last value from the most recent session.',
  },
  unavailable: {
    label: 'Unavailable',
    help: 'No provider could supply this value. Nothing has been substituted in its place.',
  },
};

export function StatusChip({
  status,
  asOf,
  source,
  className,
  showLabel = true,
}: {
  status: DataStatus;
  asOf?: string | null;
  source?: string;
  className?: string;
  showLabel?: boolean;
}) {
  const copy = STATUS_COPY[status];

  return (
    <Tooltip
      content={
        <div className="space-y-1">
          <div className="font-semibold">{copy.label}</div>
          <div>{copy.help}</div>
          {source && <div>Source: {source}</div>}
          {asOf && (
            <div>
              As of {istTime(asOf)} IST · {relativeTime(asOf)}
            </div>
          )}
        </div>
      }
    >
      <span
        className={cn(
          'inline-flex select-none items-center gap-1 rounded-full px-1.5 py-0.5 text-2xs font-medium',
          status === 'live' && 'bg-live/15 text-live',
          status === 'delayed' && 'bg-delayed/15 text-delayed',
          status === 'closed' && 'bg-stale/15 text-stale',
          status === 'unavailable' && 'bg-destructive/15 text-destructive',
          className,
        )}
      >
        <span
          aria-hidden
          className={cn(
            'h-1.5 w-1.5 rounded-full bg-current',
            status === 'live' && 'animate-pulse-dot',
          )}
        />
        {showLabel && copy.label}
      </span>
    </Tooltip>
  );
}

// ── provenance chip (Market data / Calculated / Signal / AI) ───────────────

const PROVENANCE_COPY: Record<Provenance, { label: string; help: string; className: string }> = {
  market_data: {
    label: 'Market data',
    help: 'Observed directly from an exchange or broker feed.',
    className: 'bg-primary/10 text-primary',
  },
  calculated: {
    label: 'Calculated',
    help: 'Computed deterministically from market data. The formula is shown wherever this value appears.',
    className: 'bg-secondary text-secondary-foreground',
  },
  rule_signal: {
    label: 'Rule signal',
    help: 'Output of the rule engine. It reports which conditions currently agree — it is not a forecast.',
    className: 'bg-delayed/15 text-delayed',
  },
  ai_interpretation: {
    label: 'AI interpretation',
    help: 'Narration generated by a language model over verified data. Every number in it is checked against the evidence.',
    className: 'bg-accent text-accent-foreground',
  },
  user_input: {
    label: 'Your input',
    help: 'Supplied by you, not sourced from the market.',
    className: 'bg-muted text-muted-foreground',
  },
};

export function ProvenanceChip({ kind, className }: { kind: Provenance; className?: string }) {
  const copy = PROVENANCE_COPY[kind];
  return (
    <Tooltip content={copy.help}>
      <span
        className={cn(
          'inline-flex select-none items-center rounded px-1.5 py-0.5 text-2xs font-medium',
          copy.className,
          className,
        )}
      >
        {copy.label}
      </span>
    </Tooltip>
  );
}

// ── unavailable ─────────────────────────────────────────────────────────────

export function Unavailable({
  reason,
  detail,
  attempted,
  compact = false,
  className,
}: {
  reason?: string;
  detail?: string;
  attempted?: Array<{ provider: string; error: string }>;
  compact?: boolean;
  className?: string;
}) {
  const body = (
    <div className="space-y-1.5">
      <div className="font-semibold">Live market data unavailable</div>
      {detail && <div>{detail}</div>}
      {reason && <div className="opacity-80">Reason code: {reason}</div>}
      {attempted && attempted.length > 0 && (
        <div>
          <div className="mt-1 font-medium">Providers attempted:</div>
          <ul className="mt-0.5 space-y-0.5">
            {attempted.map((a) => (
              <li key={a.provider}>
                {a.provider}: {a.error}
              </li>
            ))}
          </ul>
        </div>
      )}
      <div className="mt-1 opacity-80">No value has been estimated or substituted.</div>
    </div>
  );

  if (compact) {
    return (
      <Tooltip content={body}>
        <span
          className={cn(
            'inline-flex items-center gap-1 text-2xs font-medium text-muted-foreground',
            className,
          )}
        >
          <AlertCircle className="h-3 w-3" aria-hidden />
          Unavailable
        </span>
      </Tooltip>
    );
  }

  return (
    <div
      className={cn(
        'inline-flex items-start gap-1.5 rounded-md border border-dashed border-border',
        'bg-muted/30 px-2 py-1.5 text-xs text-muted-foreground',
        className,
      )}
    >
      <AlertCircle className="mt-0.5 h-3.5 w-3.5 shrink-0" aria-hidden />
      <div>
        <div className="font-medium text-foreground">Live market data unavailable</div>
        {detail && <div className="mt-0.5 leading-relaxed">{detail}</div>}
      </div>
    </div>
  );
}

// ── the main component ──────────────────────────────────────────────────────

export interface DataValueProps<T> {
  data: Sourced<T> | null | undefined;
  /** Render the available value. */
  children: (value: T) => React.ReactNode;
  /** Show the freshness chip beside the value. */
  showStatus?: boolean;
  /** Show the market-data / calculated / signal chip. */
  showProvenance?: boolean;
  /** Compact rendering for table cells. */
  compact?: boolean;
  className?: string;
  /** Rendered while `data` is undefined (still loading). */
  fallback?: React.ReactNode;
}

export function DataValue<T>({
  data,
  children,
  showStatus = false,
  showProvenance = false,
  compact = false,
  className,
  fallback,
}: DataValueProps<T>) {
  if (data === null || data === undefined) {
    return <>{fallback ?? <span className="text-muted-foreground">…</span>}</>;
  }

  if (!isAvailable(data)) {
    return (
      <Unavailable
        {...(data.reason !== undefined ? { reason: data.reason } : {})}
        {...(data.detail !== undefined ? { detail: data.detail } : {})}
        {...(data.attempted !== undefined ? { attempted: data.attempted } : {})}
        compact={compact}
        {...(className !== undefined ? { className } : {})}
      />
    );
  }

  return (
    <span className={cn('inline-flex items-center gap-1.5', className)}>
      {children(data.value)}
      {showStatus && (
        <StatusChip status={data.status} asOf={data.asOf} source={data.source} showLabel={!compact} />
      )}
      {showProvenance && <ProvenanceChip kind={data.kind} />}
    </span>
  );
}

// ── source footer ───────────────────────────────────────────────────────────

/** The per-card attribution line: source, timestamp, status. */
export function SourceLine({
  source,
  asOf,
  status,
  extra,
  className,
}: {
  source?: string | null;
  asOf?: string | null;
  status?: DataStatus;
  extra?: React.ReactNode;
  className?: string;
}) {
  if (!source && !asOf && !status) return null;
  return (
    <div
      className={cn(
        'flex flex-wrap items-center gap-x-3 gap-y-1 text-2xs text-muted-foreground',
        className,
      )}
    >
      {source && <span>Source: {source}</span>}
      {asOf && <span>Updated: {istTime(asOf)} IST</span>}
      {status && <StatusChip status={status} asOf={asOf ?? null} {...(source ? { source } : {})} />}
      {extra}
    </div>
  );
}

// ── methodology note ────────────────────────────────────────────────────────

/** An inline "how is this computed" affordance. */
export function MethodNote({ children, className }: { children: React.ReactNode; className?: string }) {
  return (
    <Tooltip content={children} className={className}>
      <button
        type="button"
        aria-label="How this is calculated"
        className="text-muted-foreground/70 transition-colors hover:text-foreground"
      >
        <Info className="h-3 w-3" aria-hidden />
      </button>
    </Tooltip>
  );
}

// ── a labelled metric row, the workhorse of the detail panels ──────────────

export function Metric({
  label,
  value,
  sub,
  method,
  className,
  valueClassName,
}: {
  label: string;
  value: React.ReactNode;
  sub?: React.ReactNode;
  method?: React.ReactNode;
  className?: string;
  valueClassName?: string;
}) {
  return (
    <div className={cn('flex flex-col gap-0.5', className)}>
      <div className="flex items-center gap-1 text-2xs uppercase tracking-wide text-muted-foreground">
        {label}
        {method && <MethodNote>{method}</MethodNote>}
      </div>
      <div className={cn('tabular text-sm font-medium', valueClassName)}>{value}</div>
      {sub && <div className="text-2xs text-muted-foreground">{sub}</div>}
    </div>
  );
}

/** Renders an ALL_CAPS enum for display. */
export const Humanised = ({ value }: { value: string | null | undefined }) => (
  <>{humanise(value)}</>
);
