/**
 * Zerodha Kite Connect v3 provider.
 *
 * Docs: https://kite.trade/docs/connect/v3/
 *
 * Auth: api_key + api_secret produce a daily access_token via the login flow —
 * the user visits the Kite login URL, is redirected back with a request_token,
 * and `exchangeRequestToken` converts it. The token expires the next morning,
 * so the Settings UI prompts for a fresh login daily.
 *
 * Kite has no option-chain endpoint. The chain is assembled by the options
 * module from the instrument dump plus a batched quote call, which is why this
 * provider declares `optionExpiries` and `quoteBatch` but not `optionChain`.
 */
import { createHash } from 'node:crypto';
import { HttpProvider, num, isoOrNow } from '../base/HttpProvider.js';
import { ProviderError } from '../../utils/errors.js';
import type {
  MarketDataProvider,
  ProviderManifest,
  ProviderCredentials,
  QuoteRequest,
  CandleRequest,
  NormalizedQuote,
  NormalizedCandle,
  NormalizedInstrument,
  ProviderId,
  Exchange,
  InstrumentType,
} from '../types.js';
import { symbolKey } from '../types.js';
import type { Timeframe } from '../../utils/time.js';

const KITE_INTERVAL: Record<Timeframe, string | null> = {
  '1m': 'minute',
  '5m': '5minute',
  '15m': '15minute',
  '30m': '30minute',
  '1h': '60minute',
  '4h': null, // aggregated locally from 60minute
  '1d': 'day',
  '1w': null, // aggregated locally from day
  '1M': null,
};

interface KiteEnvelope<T> {
  status: 'success' | 'error';
  data?: T;
  message?: string;
  error_type?: string;
}

interface KiteQuoteLeg {
  instrument_token?: number;
  last_price?: number;
  last_quantity?: number;
  average_price?: number;
  volume?: number;
  buy_quantity?: number;
  sell_quantity?: number;
  oi?: number;
  oi_day_high?: number;
  oi_day_low?: number;
  net_change?: number;
  lower_circuit_limit?: number;
  upper_circuit_limit?: number;
  last_trade_time?: string;
  timestamp?: string;
  ohlc?: { open?: number; high?: number; low?: number; close?: number };
  depth?: {
    buy?: Array<{ price?: number; quantity?: number; orders?: number }>;
    sell?: Array<{ price?: number; quantity?: number; orders?: number }>;
  };
}

export class KiteProvider extends HttpProvider implements MarketDataProvider {
  protected readonly providerId: ProviderId = 'kite';
  protected readonly baseUrl = 'https://api.kite.trade';

  private apiKey: string | undefined;
  private apiSecret: string | undefined;
  private accessToken: string | undefined;

  readonly manifest: ProviderManifest = {
    id: 'kite',
    displayName: 'Zerodha Kite Connect',
    docsUrl: 'https://kite.trade/docs/connect/v3/',
    authModel: 'daily_oauth',
    capabilities: [
      'quote',
      'quoteBatch',
      'depth',
      'historicalCandles',
      'intradayCandles',
      'instruments',
      'optionExpiries',
      'indices',
      'holdings',
      'positions',
    ],
    credentialFields: [
      { key: 'apiKey', label: 'API Key', secret: false, required: true },
      { key: 'apiSecret', label: 'API Secret', secret: true, required: true },
      {
        key: 'accessToken',
        label: 'Access Token',
        secret: true,
        required: false,
        help: 'Generated by the daily login flow. Expires each morning (~07:30 IST).',
      },
    ],
    throttleMs: {
      default: 350, // Kite allows ~3 req/s on most endpoints
      quote: 350,
      historical: 350,
      instruments: 60_000,
    },
    notes:
      'Kite Connect is a paid subscription, and historical data is a separate add-on. Kite exposes no option-chain endpoint — the chain is assembled locally from the instrument master plus batched quotes.',
  };

  constructor(creds: ProviderCredentials = {}) {
    super();
    this.apiKey = creds.apiKey;
    this.apiSecret = creds.apiSecret;
    this.accessToken = creds.accessToken;
    this.throttle = { ...this.manifest.throttleMs };
  }

  isConfigured(): boolean {
    return Boolean(this.apiKey && this.accessToken);
  }

  private headers(): Record<string, string> {
    if (!this.isConfigured()) {
      throw new ProviderError('kite', 'Kite credentials are not configured', {
        retryable: false,
        status: 401,
      });
    }
    return {
      'X-Kite-Version': '3',
      Authorization: `token ${this.apiKey}:${this.accessToken}`,
    };
  }

  /** URL the user must visit to start the daily login. */
  loginUrl(): string {
    if (!this.apiKey) throw new ProviderError('kite', 'API key not configured', { retryable: false });
    return `https://kite.zerodha.com/connect/login?api_key=${this.apiKey}&v=3`;
  }

  /**
   * Exchange a request_token for an access_token.
   * checksum = SHA256(api_key + request_token + api_secret)
   */
  async exchangeRequestToken(requestToken: string): Promise<{ accessToken: string; userId: string }> {
    if (!this.apiKey || !this.apiSecret) {
      throw new ProviderError('kite', 'API key/secret not configured', { retryable: false });
    }
    const checksum = createHash('sha256')
      .update(this.apiKey + requestToken + this.apiSecret)
      .digest('hex');

    const body = new URLSearchParams({
      api_key: this.apiKey,
      request_token: requestToken,
      checksum,
    }).toString();

    const res = await this.http<KiteEnvelope<{ access_token: string; user_id: string }>>(
      '/session/token',
      {
        method: 'POST',
        headers: {
          'X-Kite-Version': '3',
          'content-type': 'application/x-www-form-urlencoded',
        },
        rawBody: body,
        retries: 0,
      },
    );

    if (res.status !== 'success' || !res.data?.access_token) {
      throw new ProviderError('kite', res.message ?? 'Token exchange failed', { retryable: false });
    }
    this.accessToken = res.data.access_token;
    return { accessToken: res.data.access_token, userId: res.data.user_id };
  }

  async healthCheck() {
    if (!this.isConfigured()) {
      return { ok: false, latencyMs: 0, detail: 'Credentials not configured' };
    }
    return this.probe(async () => {
      const res = await this.http<KiteEnvelope<unknown>>('/user/profile', {
        headers: this.headers(),
        retries: 0,
      });
      if (res.status !== 'success') throw new Error(res.message ?? 'profile call failed');
    });
  }

  // ── quotes ────────────────────────────────────────────────────────────────

  async getQuote(req: QuoteRequest): Promise<NormalizedQuote> {
    const [q] = await this.getQuotes([req]);
    if (!q) throw new ProviderError('kite', `No quote for ${req.tradingsymbol}`, { retryable: false });
    return q;
  }

  async getQuotes(reqs: QuoteRequest[]): Promise<NormalizedQuote[]> {
    if (reqs.length === 0) return [];

    // Kite accepts up to 500 instruments per call as repeated ?i= params.
    const chunks: QuoteRequest[][] = [];
    for (let i = 0; i < reqs.length; i += 500) chunks.push(reqs.slice(i, i + 500));

    const out: NormalizedQuote[] = [];
    for (const chunk of chunks) {
      const params = chunk
        .map((r) => `i=${encodeURIComponent(`${r.exchange}:${r.tradingsymbol}`)}`)
        .join('&');

      const res = await this.http<KiteEnvelope<Record<string, KiteQuoteLeg>>>(
        `/quote?${params}`,
        { headers: this.headers(), throttleGroup: 'quote' },
      );
      if (res.status !== 'success' || !res.data) {
        throw new ProviderError('kite', res.message ?? 'Quote call failed', { retryable: true });
      }

      for (const [key, leg] of Object.entries(res.data)) {
        const ltp = num(leg.last_price);
        if (ltp === null) continue;
        const [exchange = 'NSE', tradingsymbol = key] = key.split(':');
        const ohlc = leg.ohlc ?? {};
        const bid = leg.depth?.buy?.[0];
        const ask = leg.depth?.sell?.[0];

        out.push({
          symbol: symbolKey(exchange, tradingsymbol),
          exchange: exchange as Exchange,
          tradingsymbol,
          ltp,
          prevClose: num(ohlc.close),
          open: num(ohlc.open),
          high: num(ohlc.high),
          low: num(ohlc.low),
          close: num(ohlc.close),
          volume: num(leg.volume),
          avgPrice: num(leg.average_price),
          oi: num(leg.oi),
          oiChange: null,
          bid: num(bid?.price),
          ask: num(ask?.price),
          bidQty: num(bid?.quantity),
          askQty: num(ask?.quantity),
          upperCircuit: num(leg.upper_circuit_limit),
          lowerCircuit: num(leg.lower_circuit_limit),
          week52High: null,
          week52Low: null,
          timestamp: isoOrNow(leg.timestamp ?? leg.last_trade_time),
          providerToken: leg.instrument_token ? String(leg.instrument_token) : undefined,
        });
      }
    }
    return out;
  }

  // ── candles ───────────────────────────────────────────────────────────────

  async getCandles(req: CandleRequest): Promise<NormalizedCandle[]> {
    if (!req.providerToken) {
      throw new ProviderError('kite', `Missing Kite instrument_token for ${req.tradingsymbol}`, {
        retryable: false,
      });
    }
    const interval = KITE_INTERVAL[req.timeframe];
    if (!interval) {
      throw new ProviderError(
        'kite',
        `Timeframe ${req.timeframe} is aggregated locally, not requested from Kite`,
        { retryable: false },
      );
    }

    const fmt = (d: Date) => d.toISOString().slice(0, 19).replace('T', ' ');
    const res = await this.http<KiteEnvelope<{ candles: unknown[][] }>>(
      `/instruments/historical/${req.providerToken}/${interval}`,
      {
        headers: this.headers(),
        query: { from: fmt(req.from), to: fmt(req.to), oi: 1 },
        throttleGroup: 'historical',
      },
    );
    if (res.status !== 'success' || !res.data?.candles) {
      throw new ProviderError('kite', res.message ?? 'Historical call failed', { retryable: true });
    }

    // Row shape: [timestamp, open, high, low, close, volume, oi?]
    const out: NormalizedCandle[] = [];
    for (const row of res.data.candles) {
      const open = num(row[1]);
      const high = num(row[2]);
      const low = num(row[3]);
      const close = num(row[4]);
      if (open === null || high === null || low === null || close === null) continue;
      out.push({
        ts: isoOrNow(row[0] as string),
        open,
        high,
        low,
        close,
        volume: num(row[5]) ?? 0,
        oi: num(row[6]),
      });
    }
    return out;
  }

  // ── instruments ───────────────────────────────────────────────────────────

  async getInstruments(): Promise<NormalizedInstrument[]> {
    const csv = await this.http<string>('/instruments', {
      headers: this.headers(),
      raw: true,
      throttleGroup: 'instruments',
      timeoutMs: 120_000,
    });
    return parseKiteInstruments(csv);
  }
}

/**
 * Kite instrument dump columns:
 * instrument_token, exchange_token, tradingsymbol, name, last_price, expiry,
 * strike, tick_size, lot_size, instrument_type, segment, exchange
 */
export function parseKiteInstruments(csv: string): NormalizedInstrument[] {
  const lines = csv.split(/\r?\n/).filter((l) => l.trim());
  if (lines.length < 2) return [];
  const header = lines[0]!.split(',').map((h) => h.trim());
  const idx = (n: string) => header.indexOf(n);

  const iToken = idx('instrument_token');
  const iSymbol = idx('tradingsymbol');
  const iName = idx('name');
  const iExpiry = idx('expiry');
  const iStrike = idx('strike');
  const iTick = idx('tick_size');
  const iLot = idx('lot_size');
  const iType = idx('instrument_type');
  const iSegment = idx('segment');
  const iExchange = idx('exchange');

  const out: NormalizedInstrument[] = [];
  for (let i = 1; i < lines.length; i += 1) {
    const f = lines[i]!.split(',');
    const token = f[iToken]?.trim();
    const tradingsymbol = f[iSymbol]?.trim().toUpperCase();
    const exchange = f[iExchange]?.trim().toUpperCase() as Exchange | undefined;
    if (!token || !tradingsymbol || !exchange) continue;

    const rawType = (f[iType] ?? '').trim().toUpperCase();
    let instrumentType: InstrumentType = 'EQ';
    if (rawType === 'CE' || rawType === 'PE') instrumentType = rawType;
    else if (rawType === 'FUT') instrumentType = 'FUT';
    else if ((f[iSegment] ?? '').toUpperCase() === 'INDICES') instrumentType = 'INDEX';

    const expiry = (f[iExpiry] ?? '').trim();

    out.push({
      exchange,
      tradingsymbol,
      name: (f[iName] ?? '').trim() || null,
      isin: null,
      segment: (f[iSegment] ?? '').trim() || null,
      instrumentType,
      underlying: (f[iName] ?? '').trim().toUpperCase() || null,
      expiry: expiry || null,
      strike: num(f[iStrike]),
      optionType: rawType === 'CE' || rawType === 'PE' ? rawType : null,
      lotSize: num(f[iLot]) ?? 1,
      tickSize: num(f[iTick]) ?? 0.05,
      providerToken: token,
    });
  }
  return out;
}
